#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

# Commented out the only 2 valid lines below as they are obsolete.

# PROJECT_NAME := i2c-daisy-chain

# include $(IDF_PATH)/make/project.mk
